Repository onecx/onecx-parameter-ui, pull requests merged in 2025-07, with the labels that each got.

#238 feat: updated locations to secure open q endpoints
  nginx/locations.conf
Labels: bug, config

#242 fix: handle boolean false value, display JSON validation errors
  src/app/parameter/parameter-detail/parameter-detail.component.html
  src/app/parameter/parameter-detail/parameter-detail.component.ts
Labels: fix

#243 feat: improve displaying JSON validation error
  src/app/parameter/parameter-detail/parameter-detail.component.html
  src/app/parameter/parameter-detail/parameter-detail.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: feature

#246 feat: display usage details
  src/app/parameter/detail-history/detail-history-list/detail-history-list.component.html
  src/app/parameter/detail-history/detail-history.component.scss
  src/app/parameter/parameter-detail/parameter-detail.component.spec.ts
  src/app/parameter/parameter-detail/parameter-detail.component.ts
  src/app/parameter/parameter-search/parameter-search.component.html
  src/app/parameter/parameter-search/parameter-search.component.spec.ts
  src/app/parameter/parameter.module.ts
  src/app/parameter/usage-detail/usage-detail-criteria/usage-detail-criteria.component.html
  src/app/parameter/usage-detail/usage-detail-criteria/usage-detail-criteria.component.spec.ts
  src/app/parameter/usage-detail/usage-detail-criteria/usage-detail-criteria.component.ts
  src/app/parameter/usage-detail/usage-detail-list/usage-detail-list.component.html
  src/app/parameter/usage-detail/usage-detail-list/usage-detail-list.component.spec.ts
  src/app/parameter/usage-detail/usage-detail-list/usage-detail-list.component.ts
  src/app/parameter/usage-detail/usage-detail.component.html
  src/app/parameter/usage-detail/usage-detail.component.scss
  src/app/parameter/usage-detail/usage-detail.component.spec.ts
  src/app/parameter/usage-detail/usage-detail.component.ts
  src/app/parameter/usage-search/usage-search.component.html
  src/app/parameter/usage-search/usage-search.component.scss
  src/app/parameter/usage-search/usage-search.component.spec.ts
  src/app/parameter/usage-search/usage-search.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: feature
